<a href="https://colab.research.google.com/github/mahmoudwaheed93/ITI/blob/main/Pandas%2BPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [22]:
# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import pandas
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/Data/Purchase_Data.csv'
df_data = pd.read_csv(file_path)


print("CSV file loaded successfully! Here are the first few rows:")
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CSV file loaded successfully! Here are the first few rows:
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

Use the dtypes attribute to view how each column is stored

In [23]:
#Write your code here
#View dtypes of columns

display(df_data.dtypes)

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

In [24]:
#Write you code here
result_1 = df_data.loc[:, df_data.columns[:2]]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [25]:
#Write you code here
# Slice the first two rows using .loc
result_2 = df_data.loc[:1, :]
display(result_2)

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

## Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [26]:
#Write your code here

result_3 = df_data.loc[:3, df_data.columns[:5]]
display(result_3)

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [29]:
#Write your code here
# Slice rows 0,4,6 and columns Age and Fare
result_4 = df_data.loc[[0, 4, 6], ["invoice_time", "price"]]
display(result_4)

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [31]:
# Store the number rows in a variable called num_rows.
num_rows = df_data.shape[0]

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [32]:
#Write your code here
# Print out the last row of the dataframe
last_row = df_data.loc[num_rows - 1, :]
display(last_row)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [33]:
#Write your code here
# Compute the average and max price charged.
avg_price = df_data['price'].mean()
max_price = df_data['price'].max()

print(f"Average price: {avg_price}")
print(f"Maximum price: {max_price}")

Average price: 3.1920522110741363
Maximum price: 6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [35]:
# Compute average price and average number of items purchased
avg_price, avg_num_items = df_data[["price", "num_item"]].mean()
print("Average price:", avg_price)
print("Average num_item:", avg_num_items)

Average price: 3.1920522110741363
Average num_item: 1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [36]:
#Write your code here
# Create a new column "total"
df_data["total"] = df_data["price"] * df_data["num_item"]
display(df_data.head())

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [37]:
#Write your code here
# Get the 3 most expensive purchases and compute their average price
avg_top3_price = df_data["price"].nlargest(3).mean()
print("Average price of the 3 most expensive purchases:", avg_top3_price)

Average price of the 3 most expensive purchases: 6.003333333333333

How many different products are there?

In [43]:
#Write your code here
# Number of different products
num_products = df_data["product_id"].nunique()
print("Number of different products:", num_products)

Number of different products: 53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [44]:
#Write your code here
# Get descriptive statistics
stats = df_data["total"].describe()

# Compute the difference between mean and median
difference = stats["mean"] - stats["50%"]
print("Difference between mean and median of total:", difference)

Difference between mean and median of total: 0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [45]:
#Write your code here
# Drop the column 'total'
df_data = df_data.drop("total", axis=1)
display(df_data.head())

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

In [49]:
#Write your code here
# Convert 'invoice time' column to datetime
df_data["invoice_time"] = pd.to_datetime(df_data["invoice_time"])
print(df_data.dtypes)

/tmp/ipython-input-3114554687.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data["invoice_time"] = pd.to_datetime(df_data["invoice_time"])

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [56]:
#Write your code here
# Convert 'invoice time' column to datetime
df_data["invoice_time"] = pd.to_datetime(df_data["invoice_time"])

# Print out the new column types
print(df_data.dtypes)

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [57]:
#Write your code here
# Create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.
df_data['DOW'] = df_data['invoice_time'].dt.day_name()
df_data['Month'] = df_data['invoice_time'].dt.month_name()

# Print the head of the dataframe to make sure this was done correctly.
display(df_data.head())

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,July
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,July
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,July
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,July
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,July

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [72]:
#Write your code here
# Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?
dow_counts = df_data['DOW'].value_counts()
num_purchases_wed = dow_counts['Wednesday']

print(f"Number of purchases made on Wednesday: {num_purchases_wed}")

Number of purchases made on Wednesday: 959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [99]:
#Write your code here

# Read in the data frame
# Please update the file path if necessary
df_titanic = pd.read_csv('/content/drive/MyDrive/Data/titanic_Data.csv')

# Use the head() method to check that it was read in correctly.
display(df_titanic.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data/titanic_Data.csv'

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [88]:
#Write your code here

# Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".
df_titanic = df_titanic.rename(columns={"Name": "Passenger_Name", "Ticket": "Ticket_Num"})

# Display the head to verify the changes
display(df_titanic.head())

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Change the index of the df_titanic to the column PasengerID.

In [98]:
#Write your code here

# Change the index of the df_titanic to the column PasengerID.
# Make sure you have loaded the correct Titanic dataset (titanic.csv) into df_titanic first.
df_titanic = df_titanic.set_index('PassengerId')

# Display the head to verify the changes
display(df_titanic.head())

KeyError: "None of ['PassengerId'] are in the columns"

Select the name of passenger 896

In [102]:
#Write your code here
# Select the name of passenger 896
passenger_name_896 = df_titanic.loc[896, 'Passenger_Name']

print(f"The name of passenger 896 is: {passenger_name_896}")

KeyError: 'Passenger_Name'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [103]:
#Write your code here

# Change the index back to row numbers but making sure that we don't lose the PassengerId column.
df_titanic = df_titanic.reset_index()

# Display the head to verify the changes
display(df_titanic.head())

,level_0,index,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,0,0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,1,1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2,2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,3,3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,4,4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [104]:
#Write you code here

# Count the number of missing entries in the Age column
missing_age_count = df_titanic['Age'].isnull().sum()

print(f"Number of missing entries in the Age column: {missing_age_count}")

KeyError: 'Age'

Compute the avg age of passengers ignoring the missing data.

In [106]:
#Write your code here
# Compute the average age ignoring missing data
avg_age = df_titanic["Age"].mean()
print("Average age of passengers:", avg_age)

KeyError: 'Age'

Using the fillna() method replace the missing values in the Age column with the mean.

In [107]:
#Write your code here

# Compute the mean of the Age column, ignoring missing values
mean_age = df_titanic['Age'].mean()

# Fill missing values in the Age column with the mean
df_titanic['Age'] = df_titanic['Age'].fillna(mean_age)

# Display the head to verify the changes (optional, but good practice)
display(df_titanic.head())

# You can also check if there are any remaining missing values in the Age column
print(f"\nNumber of remaining missing values in Age column: {df_titanic['Age'].isnull().sum()}")

KeyError: 'Age'

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [108]:
#Write your code here

# Find the average age of the 5 oldest passengers
# Sort by age in descending order, select the top 5, and calculate the mean of the Age column
average_age_top_5_oldest = df_titanic.nlargest(5, 'Age')['Age'].mean()

print(f"The average age of the 5 oldest passengers is: {average_age_top_5_oldest}")

KeyError: 'Age'

In [101]:
# Find the average price of the three most expensive purchases
avg_price_top_3 = df_data.nlargest(3, 'price')['price'].mean()
print(f"The average price of the three most expensive purchases is: {avg_price_top_3}")

The average price of the three most expensive purchases is: 6.003333333333333

In [95]:
# Change the index back to row numbers but making sure that we don't lose the PassengerId column.
df_titanic = df_titanic.reset_index()

# Display the head to verify the changes
display(df_titanic.head())

,index,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0